# This workflow builds a .deb package when a version is pushed.

name: build-deb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get version from tag name
        id: version
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      # Create the package contents directory structure
      - name: Assemble package contents
        id: assemble
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp/debpkg/DEBIAN
          mkdir -p $GITHUB_WORKSPACE/tmp/debpkg/opt/quartersbrief
          cp -r $GITHUB_WORKSPACE/src $GITHUB_WORKSPACE/tmp/debpkg/opt/quartersbrief
          # cp -r $GITHUB_WORKSPACE/assets $GITHUB_WORKSPACE/tmp/debpkg/opt/quartersbrief
          cp $GITHUB_WORKSPACE/package.json $GITHUB_WORKSPACE/tmp/debpkg/opt/quartersbrief
          cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/tmp/debpkg/opt/quartersbrief
          echo "::set-output name=pkgroot::$GITHUB_WORKSPACE/tmp/debpkg"

      # Create .deb control scripts
      - name: Create postinst
        run: |
          echo "cd /opt/quartersbrief && npm install --production 1> /dev/null 2> /dev/null &&> npm link" > ${{ steps.assemble.outputs.pkgroot }}/DEBIAN/postinst && chmod +x ${{ steps.assemble.outputs.pkgroot }}/DEBIAN/postinst

      - name: Build .deb package
        uses: jiro4989/build-deb-action@v2
        id: package
        with:
          package: quartersbrief
          package_root: ${{ steps.assemble.outputs.pkgroot }}
          version: ${{ steps.version.outputs.non-prefixed }}
          maintainer: 'BadIdeaException'
          arch: 'amd64'
          depends: 'nodejs (>= 17.0.0), wine, python3'

      - name: Upload package to release
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.package.outputs.file_name }}
          release-tag: ${{ github.ref }}
