# This is a basic workflow to help you get started with Actions

name: build-deb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Remove unwanted development-related stuff from the checked out repository.
      - name: Remove development-related files
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf gamedata-jsdoc grunt test
          rm .eslintrc.json .gitignore Gruntfile.cjs Vagrantfile *sublime*

      - uses: jiro4989/build-deb-action@v2
        with:
          package: quartersbrief_${{ github.ref_name }}
          package_root: $GITHUB_REPO
          maintainer: 'BadIdeaException'
          arch: 'amd64'
          depends: 'nodejs (>= 17.0.0), wine, python3'